[tool.poetry]
name = "semiring_einsum"
version = "0.1.0"
description = "Generic implementation of einsum in PyTorch that supports different semirings"
authors = ["Brian DuSell"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.3"

[tool.poetry.dev-dependencies]
sphinx = "^2.2"
sphinxcontrib-bibtex = "^1.0"
sphinx-autodoc-typehints = "^1.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
